### ISSUE TITLE
Left blocks with is-centered modifier aren't centered

### ISSUE THREAD

**Issue by FlorentinBurgeat** [Wikiki/bulma-timeline#15]
The left blocks of the timeline stay on the left of the window and are not stick to the timeline.

You can reproduce it by removing the code section next to the example in the doc.

**Comment by Wikiki** [comment]
Hi,

What browser / os are you using ?
I can't reproduce it on my laptop.

Are you able to reproduce it in  a codepen ?

**Comment by FlorentinBurgeat** [comment]
I'm on windows 10 with Chrome.

Just found what to fix:

It's missing:
`.timeline.is-centered .timeline-item {
justify-content: flex-end
}`

**Comment by Wikiki** [comment]
Thanks for the fix.
I'll add it.

**Comment by FlorentinBurgeat** [comment]
Okay it moves the right items to the right of the window just doing this :/. You should maybe add a class to indicate if the block is on the right or left of the timeline and switch between flex-start and flex-end..

**Comment by FlorentinBurgeat** [comment]
or just add the nth-child selector, `.timeline.is-centered .timeline-item:nth-child(2n) { justify-content: flex-end }` It will fix all of it easily.

**Comment by Wikiki** [comment]
I'm using the selector :nth-of-type(2n) and :nth-of-type(2n+1) to align them.
Using :nth-of-type instead of nth-child let the possibility to use headers  and keep the right alignment.

**Comment by FlorentinBurgeat** [comment]
Oh okay. I tried to put a header between each timeline-item but it appeared that every item were placed on the right side because the header was also a <li> and considered the left element. But it works better if I replace the li.timeline-header by a div.timeline-header. Too bad there's not nth-of-class selector.

But I think it could be a good feature to be able to specify the side we want the item to be placed.

(BTW There's two other things i want to report but i will create issues for it)

**Comment by Wikiki** [comment]
Hi,

I've updated the structure to handle is-centered correctly.

Regards

**Comment by FlorentinBurgeat** [comment]
Same screen as my other post, but I just updated and the issue is still here :/

![image](https://user-images.githubusercontent.com/15621001/32299721-e9d853c2-bf56-11e7-86fe-9faaa4d9794d.png)

**Comment by Wikiki** [comment]
It should be fixed now.
Sorry about the delay. I had not access to a large screen before today.
