### ISSUE TITLE
timeline-marker on is-centered is not centered on the border

### ISSUE THREAD

**Issue by FlorentinBurgeat** [Wikiki/bulma-timeline#16]
The right elements only on a is-centered timeline have their timeline-marker a little too on the right.
I think a position left of -43em (instead of -35em) renders better.

**Comment by Wikiki** [comment]
Fixed

**Comment by FlorentinBurgeat** [comment]
Hey, I'm sorry but now it's the left blocks markers that are a little too on the left :/
![image](https://user-images.githubusercontent.com/15621001/32299607-7e0e23a6-bf56-11e7-98d2-d940ba9c0560.png)

**Comment by Wikiki** [comment]
The point is marker position is calculated with the following rule:
<code>-(($timeline-marker-size / 2) - $timeline-marker-border-size / 2)</code>

But I forgot to take into account the .1em margin added to the left content.
