### ISSUE TITLE
Headers with a long text goes out of window on left and right timelines

### ISSUE THREAD

**Issue by FlorentinBurgeat** [Wikiki/bulma-timeline#17]
If a header is too long, it stays centered on the axe of the timeline, and so the left part of the header goes out of the window.

Windows 10/ Chrome

**Comment by Wikiki** [comment]
This behavior is related to Bulma.io tag element which is not multiline.
Try adding a max-width to header and use something else than tag element to style it.

**Comment by FlorentinBurgeat** [comment]
I made those fix to solve the issues 15,16 and 17 on my project. Tell me what you think of them :) (scss style)

```
.timeline.is-centered .timeline-item:nth-of-type(2n) {
  justify-content: flex-end;
  .timeline-marker {
    right: -0.43em;
  }
}
.timeline:not(.is-centered):not(.is-rtl) {
  .timeline-header {
    justify-content: flex-start;
    margin-left: 1em;
  }
}

.timeline.is-rtl {
  .timeline-header {
    justify-content: flex-end;
    margin-right: 1em;
  }
}
```

**Comment by Wikiki** [comment]
The point is marker position is calculated with the following rule:
<code>-(($timeline-marker-size / 2) - $timeline-marker-border-size / 2)</code>

But I forgot to take into account the .1em margin added to the left content.
It's been corrected

**Comment by FlorentinBurgeat** [comment]
No problem ;) You may have forget to change the version number though. I'm still on 1.0.3 which was before your new fixes.
