### ISSUE TITLE
Add a JSFiddle!

### ISSUE THREAD

**Issue by gustavo-depaula** [Wikiki/bulma-timeline#2]

**Comment by Wikiki** [comment]
Done Thanks for thz remark

**Comment by Wikiki** [comment]
Sorry, bad manipulation.
I'm working on it (I'm in holidays and I don't have access to my computed code).

**Comment by Wikiki** [comment]
Hi again,

You can find a demo here: https://codepen.io/anon/pen/MvJKrR
