### ISSUE TITLE
Large text width in <LI> doesn't return on line

### ISSUE THREAD

**Issue by BartRennes** [Wikiki/bulma-timeline#20]
Dear,

Using bulma css + this great timeline, i'm using the timeline in <container><columns><column is-three-quarters>, when large text is populated there is no automatic line return, it expand on right without horizontal scroll.
Any idea ?

Regards

**Comment by Wikiki** [comment]
Hi @BartRennes ,

can you please provide a [codePen](https://codepen.io) with your example ?

Regards

**Comment by BartRennes** [comment]
Thank you for your answer, it was a mistake on me ;)
(Some mondays are better than other)...
