### ISSUE TITLE
centered timelines - right aligned items are not properly showing is- colors

### ISSUE THREAD

**Issue by acidjazz** [Wikiki/bulma-timeline#25]
example: 
![image](https://user-images.githubusercontent.com/967369/39853366-7f093d9c-53e7-11e8-9ec7-168d27a82a40.png)

this one was given `.timeline-item.is-success`

and again given `.timeline-item.is-primary`

![image](https://user-images.githubusercontent.com/967369/39853371-866f7ca4-53e7-11e8-9e5e-40983a2aeb0c.png)

**Comment by Wikiki** [comment]
Fixed feab6be
