### ISSUE TITLE
Changelog for 3.0.0

### ISSUE THREAD

**Issue by peterbe** [Wikiki/bulma-timeline#28]
At the time of writing, there's a [3.0.0 on npmjs](https://www.npmjs.com/package/bulma-timeline) but there's no such [release in GitHub](https://github.com/Wikiki/bulma-timeline/releases). 

Are there breaking backwards compat changes?

**Comment by Wikiki** [comment]
Hi,

sorry I had an issue with my release process.
There is no breaking change on this version. It's just a version number alignment because I refactored the build/release process with semantic-release
