### ISSUE TITLE
Custom colors not detected

### ISSUE THREAD

**Issue by ckz8780** [Wikiki/bulma-timeline#35]
Assuming I've created some custom colors like so: 

```
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/derived-variables";

$revenue: #19B99A;
...others

$revenue-invert: findColorInvert($revenue);
...others

$addColors: (
    "revenue":($revenue, $revenue-invert),
    ...others
);

$colors: map-merge($colors, $addColors);

@import "~bulma/bulma";
@import "~bulma-timeline";
```

Is there any way to get the timeline (and other extensions, like tooltips) to pick up my custom colors, so I can do things like `timeline-item is-revenue`? 

The custom colors work across the rest of Bulma, but it seems they aren't picked up by the extensions. 

Any thoughts? Thanks!

**Edit:** It seems if I import the sass file directly then my custom colors are picked up: `@import "~bulma-timeline/dist/css/bulma-timeline";` Is this the correct way to do it? Should I be importing this file or the index.sass file from the src directory? FWIW this is in a React/Django project with Webpack. Please do let me know if there's any info I can clarify for you. Thanks!

**Comment by Wikiki** [comment]
Hi,

it's because by default the imported file is the css one so new sass variables are not taken into account.

<code>package.json</code> contains rule <code>"style": "./dist/css/bulma-carousel.min.css",</code>

I'm wondering what's the best: let css file as default or set sass file instead ?

**Comment by ckz8780** [comment]
Thanks!
