### ISSUE TITLE
Change license from GPL to MIT or LGPL

### ISSUE THREAD

**Issue by giflw** [Wikiki/bulma-timeline#5]
HI @Wikiki 

I've noticed that you use GPLv3 license, but Bulma uses MIT. As far as I known, GPLv3 forces all the code on which the GPL part is used to become GPL. Maybe this reduces the use of the extensions as it can impose some restrictions to adopting extensions on private software scenarios.

Other option would be switch to LGPLv3, as it forces only your code as GPL, but allow all other parts to be anything else.

This would apply to all Bulma extensions.

Best regards

**Comment by Wikiki** [comment]
Changed ti MIT.
Thanks for your help
