### ISSUE TITLE
Add all extensions to one repository with one sass file as entry point

### ISSUE THREAD

**Issue by giflw** [Wikiki/bulma-timeline#6]
Hi @Wikiki 

I don't know where to ask for this, so I'm asking here.

Could you keep a repository with all extensions and a version number for easy integration with other projects as well easy modifications tracking?

I've created a repo using yours as submodules (https://github.com/giflw/bulma-extensions-all). You can use it as you wish. If you want, I can give pull access to it. But would be nice to have the all extensions repo under your username.

Best regards

**Comment by Wikiki** [comment]
Great idea :-)
I'll do it when I'll back from holidays

**Comment by Wikiki** [comment]
Done. Repo is available here: https://github.com/Wikiki/bulma-extensions

**Comment by giflw** [comment]
Thanks =D
