### ISSUE TITLE
Marker displayed awry after the latest update

### ISSUE THREAD

**Issue by yarbshk** [Wikiki/bulma-timeline#9]
Hi @Wikiki. I have noticed (on the [extension website](https://wikiki.github.io/bulma-extensions/timeline)) that the `timeline-marker` element with icon is awry displayed after the latest update (see screenshot below):
![screenshot from 2017-09-17 13-07-02](https://user-images.githubusercontent.com/19223363/30519876-971bdcec-9ba9-11e7-91ac-d7fd9446c090.png)
I use the Opera 46.0 browser. Hope it'll help.

**Comment by Wikiki** [comment]
Hi @yarbshk ,

it should works now.

Regards,
